"""
Napisz funkcję, która będzie przyjmowała 2 argumenty obowiązkowe: m i n. Niech wypisze w konsoli tabliczkę mnożenia o
rozmiarach m×n w postaci:

  1  2  3  4 ...
  2  4  6  8 ...
  3  6  9 12 ...
  4  8 12 16 ...
  ...
"""
